"""CAT-related resources bundled with NanoGraph PathFinder."""

from __future__ import annotations

import base64
import io
from typing import Final

_DEN_WFST_BASE64: Final[str] = (
    "1v2yfgYAAAB2ZWN0b3IIAAAAc3RhbmRhcmQCAAAAAAAAAAMAAAIABQAAAAAAAAAAAAAJAAAAAAAAAAAA"
    "AAAAAAAAAACAfwIAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAIAAAABAAAAAAAAAAEAAAAAAIB/BAAAAAAA"
    "AAACAAAAAAAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAgAAAAMAAAACAAAAVJ+MPwMAAAAFAAAABAAAAB+Z"
    "zz4EAAAAAACAfwMAAAAAAAAAAQAAAAAAAAAAAAAAAgAAAAMAAAACAAAAVJ+MPwMAAAAFAAAABAAAAB+Z"
    "zz4EAAAAAACAfwMAAAAAAAAAAwAAAAAAAAAAAAAAAwAAAAEAAAAAAAAAAAAAAAUAAAACAAAAAQAAAAAA"
    "AAABAAAAGHIxPwMAAAAAAAAABQAAAAAAAAAAAAAABAAAAAEAAAAAAAAAAAAAAAYAAAAEAAAAAwAAABhy"
    "MT8HAAAAAACAfwIAAAAAAAAAAQAAAAAAAAAAAAAABQAAAAIAAAABAAAAAAAAAAEAAAAYcjE/AgAAAAAA"
    "AAABAAAAAAAAAAAAAAAGAAAABAAAAAMAAAAYcjE/BwAAAAAAgH8DAAAAAAAAAAQAAAAAAAAAAAAAAAcA"
    "AAABAAAAAAAAAAAAAAAIAAAAAgAAAAEAAAAAAAAAAQAAAAAAgH8CAAAAAAAAAAEAAAAAAAAAAAAAAAgA"
    "AAACAAAAAQAAAAAAAAABAAAA"
)
_DEN_WFST_BYTES: Final[bytes] = base64.b64decode(_DEN_WFST_BASE64.encode("ascii"))


def denominator_wfst_bytes() -> bytes:
    """Return the bundled CAT denominator WFST as raw bytes."""

    return _DEN_WFST_BYTES


def denominator_wfst_stream():
    """Open the bundled CAT denominator WFST as a binary stream."""

    return io.BytesIO(_DEN_WFST_BYTES)


__all__ = ["denominator_wfst_bytes", "denominator_wfst_stream"]